import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getTrendingGifts } from '../services/getTrendingGifts'
import styles from '../styles/Home.module.scss'

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>hola</p>
        <button onClick={() => console.log(data)}>herfg</button>
        <div className={styles.grid_container}>

          {data && data.map((item: any, index: any) => {
            return (<div key={index} ><img src={item.images.original.url}className="img_gipth" /> </div>)
          })}

        </div>

      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const axiosResponse = await getTrendingGifts()
  const data = axiosResponse.data.data

  return {
    props: {
      data: data
    }
  }
}

export default Home
