import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getTrendingGifts } from '../services/getTrendingGifts'
import styles from '../styles/Home.module.scss'
import SearchBar from '../components/SearchBar/SearchBar'
import { useContext } from 'react'
import { StoreContext } from '../store/StoreProvider'
import StoreProvider from '../store/StoreProvider'
import ListGiphs from '../components/listGiphs/ListGiphs'


const Home: NextPage = ({ data }: any): JSX.Element => {
  const { dispatch, store } = useContext(StoreContext)


  function handleChange(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) {
    dispatch({
      type: "SEARCH_GIPTH",
      payload: e.target.value
    })
  }
  function handleSearch(): void {
    console.log(store)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <div>
            <SearchBar onChange={handleChange} onSearch={handleSearch} />
            <ListGiphs data={data} />




          </div>

        </main>



    </div>
  )
}

export async function getServerSideProps() {
  const axiosResponse = await getTrendingGifts()
  const data = axiosResponse.data.data

  return {
    props: {
      data: data
    }
  }
}

export default Home
